package org.thealphalab.education.mapper;

import java.util.List;

import org.springframework.stereotype.Repository;
import org.thealphalab.education.model.Class_;

@Repository
public interface Class_Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 02 21:21:28 MYT 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 02 21:21:28 MYT 2020
     */
    int insert(Class_ record);
    int insertAll(List<Class_> records);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 02 21:21:28 MYT 2020
     */
    Class_ selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 02 21:21:28 MYT 2020
     */
    List<Class_> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table class
     *
     * @mbggenerated Mon Mar 02 21:21:28 MYT 2020
     */
    int updateByPrimaryKey(Class_ record);
}