package org.thealphalab.education.mapper;

import java.sql.SQLIntegrityConstraintViolationException;
import java.util.List;

import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.stereotype.Repository;
import org.thealphalab.education.model.Student;

@Repository
public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Mar 03 16:54:46 MYT 2020
     */
//    int deleteByPrimaryKey(Integer stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Mar 03 16:54:46 MYT 2020
     */
    int insert(Student record) throws DataIntegrityViolationException;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Mar 03 16:54:46 MYT 2020
     */
//    Student selectByPrimaryKey(Integer stuid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Mar 03 16:54:46 MYT 2020
     */
//    List<Student> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student
     *
     * @mbggenerated Tue Mar 03 16:54:46 MYT 2020
     */
//    int updateByPrimaryKey(Student record);
}